#Docker compose define como configurar y ejecutar 2 servivios
version: "3.9" # Version DOcker'compose

services: #lista de servicios
  web:
    image: "carlosdelgadillo/web"
    ports:
      - "5000:5000"

  suma:
    image: "carlosdelgadillo/suma"
    ports:
      - "8001:8001"